# -*- coding: utf-8 -*-
"""Копия блокнота "EDA_clients_template.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLCIO8MfGJBeusIp2_h5rqsNcetmdGme

# Клиенты авиакомпании
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score
)

RANDOM_STATE = 42
DATASET_PATH = "https://raw.githubusercontent.com/evgpat/stepik_from_idea_to_mvp/main/datasets/clients.csv"

# Загрузка данных
df = pd.read_csv(DATASET_PATH)
df.head()

# Очистка целевой переменной
df = df[df['satisfaction'].isin(['satisfied', 'neutral or dissatisfied'])]
df['satisfaction'] = df['satisfaction'].map({
'satisfied': 1,
'neutral or dissatisfied': 0
})

# Разделение на train / test
X = df.drop(['id', 'satisfaction'], axis=1)
y = df['satisfaction']


X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.25, random_state=RANDOM_STATE, stratify=y
)

# Вспомогательные функции очистки

def cap_outliers(series, q_low=0.01, q_high=0.99):
  low, high = series.quantile([q_low, q_high])
  return series.clip(low, high)

# Обработка числовых признаков

num_cols = [
'Age',
'Flight Distance',
'Departure Delay in Minutes',
'Arrival Delay in Minutes'
]

for col in num_cols:
  X_train[col] = cap_outliers(X_train[col])
  med = X_train[col].median()
  X_train[col] = X_train[col].fillna(med)
  X_test[col] = X_test[col].fillna(med)

# Обработка сервисных оценок

service_cols = [
'Inflight wifi service', 'Departure/Arrival time convenient',
'Ease of Online booking', 'Gate location', 'Food and drink',
'Online boarding', 'Seat comfort', 'Inflight entertainment',
'On-board service', 'Leg room service', 'Baggage handling',
'Checkin service', 'Inflight service', 'Cleanliness'
]

for col in service_cols:
    med = X_train[col].median()
    X_train[col] = X_train[col].fillna(med)
    X_test[col] = X_test[col].fillna(med)

    X_train[col] = X_train[col].clip(0, 5)
    X_test[col] = X_test[col].clip(0, 5)

# Категориальные признаки

cat_cols = ['Gender', 'Customer Type', 'Type of Travel', 'Class']

for col in cat_cols:
  mode = X_train[col].mode()[0]
  X_train[col] = X_train[col].fillna(mode)
  X_test[col] = X_test[col].fillna(mode)

X_train['Gender'] = X_train['Gender'].map({'Male': 0, 'Female': 1})
X_test['Gender'] = X_test['Gender'].map({'Male': 0, 'Female': 1})

X_train['Customer Type'] = X_train['Customer Type'].map({'Loyal Customer': 1, 'disloyal Customer': 0})
X_test['Customer Type'] = X_test['Customer Type'].map({'Loyal Customer': 1, 'disloyal Customer': 0})

X_train['Type of Travel'] = X_train['Type of Travel'].map({'Business travel': 1, 'Personal Travel': 0})
X_test['Type of Travel'] = X_test['Type of Travel'].map({'Business travel': 1, 'Personal Travel': 0})

X_train = pd.get_dummies(X_train, columns=['Class'], dtype=int)
X_test = pd.get_dummies(X_test, columns=['Class'], dtype=int)

X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

# Модель

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())
])

pipe.fit(X_train, y_train)

# Оценка качества

pred = pipe.predict(X_test)
proba = pipe.predict_proba(X_test)[:, 1]

print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))
print('ROC-AUC', roc_auc_score(y_test, proba))

# Feature Importance

import pandas as pd

coef = pipe.named_steps['model'].coef_[0]
features = X_train.columns

importance = pd.Series(coef, index=features).sort_values()
importance


importance.tail(10).plot(kind='barh', title='Топ позитивных факторов')
plt.show()

importance.head(10).plot(kind='barh', title='Топ негативных факторов')
plt.show()

# Улучшение качества модели

# RandomForest

from sklearn.ensemble import RandomForestClassifier


rf = RandomForestClassifier(
n_estimators=300,
max_depth=12,
random_state=RANDOM_STATE,
n_jobs=-1
)


rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_proba = rf.predict_proba(X_test)[:, 1]


print(classification_report(y_test, rf_pred))
print('ROC-AUC:', roc_auc_score(y_test, rf_proba))

# Production-ready preprocessing

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


num_cols = X.select_dtypes(include=np.number).columns.tolist()
class_cols = [col for col in X.columns if col.startswith('Class_')]
cat_cols = ['Gender', 'Customer Type', 'Type of Travel'] + class_cols


preprocessor = ColumnTransformer([
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(), cat_cols)
])


pipe_prod = Pipeline([
('prep', preprocessor),
('model', LogisticRegression(max_iter=1000))
])


pipe_prod.fit(X_train, y_train)

# Сохранение модели

import joblib

joblib.dump(pipe_prod, 'airline_satisfaction_model.pkl')